name: default
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install meson nettle-dev ninja-build libpbkdf2-tiny-perl
          meson setup build
          ninja -C build
          meson test -vC build
